### ISSUE TITLE
Switch to React for UI

### ISSUE THREAD

**Issue by bhavyaGP** [clubgamma/Internet-Speed-Tester#2]
basic react app for frontend

**Comment by nandit27** [comment]
I have created a new react app for the same with all progress till current updated so what should be my next step towards this ? @bhavyaGP

**Comment by bhavyaGP** [comment]
Go Ahead!! and Raise PR.

**Comment by nandit27** [comment]
@bhavyaGP can you assign this to me ?

**Comment by bhavyaGP** [comment]
I have gone through your code base, I highly appreciate your effort, and there is no issue in your code,
But Your Codebase isn't well structured. So make it structured like (client-server).

**Comment by nandit27** [comment]
Just give me 1-2 days and I will fix it so will it be then accepted ? @bhavyaGP
