### ISSUE TITLE
Faced Issue in running project

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/Internet-Speed-Tester#29]
im Faceing Issue in running project I followed all the steps that are mentioned in README.md file..still throw error..
![image](https://github.com/user-attachments/assets/182d2762-d0d4-45a5-b4e6-d916ea39fc5c)

**Comment by Meetpidev** [comment]
@bhavyaGP Requested to guid me how to run it...

**Comment by bhavyaGP** [comment]
Is the server running?

**Comment by Meetpidev** [comment]
@bhavyaGP no when i click on button then its show me following error..

![Screenshot 2024-10-23 191819](https://github.com/user-attachments/assets/4990a005-7701-4732-b6ce-5928f8edbb4d)

**Comment by nandit27** [comment]
You need to install fast using the command npm install -g fast-cli @Meetpidev

**Comment by nandit27** [comment]
first go in the server folder using cd server and then run this command @Meetpidev

**Comment by Meetpidev** [comment]
I already tried this in server folder by npm i fast-cli but its still showing me error....

**Comment by nandit27** [comment]
The error message clearly shows that the required module is not installed or not properly installed. Try checking the version of fast. if it doesnt show then you need to again install it.

**Comment by Meetpidev** [comment]
its showing me the verison on fast.. i uninstalled and retry to install by "npm i fast-cli" in server... stilll got this error by pressing "start speed test" button..
![image](https://github.com/user-attachments/assets/a8dd565a-754d-4375-9770-c1b10c27d041)
![image](https://github.com/user-attachments/assets/f97490bb-579d-4e14-a914-7d95814cb741)

**Comment by nandit27** [comment]
Have you pulled the code ? or is it the latest code ?

**Comment by Meetpidev** [comment]
> Have you pulled the code ? or is it the latest code ?

its latest code.. i just simply fork and clone it.. and followed all the instrucion that given in README.m .. and install fast-cli in server folder.. even though its show me same error..

**Comment by nandit27** [comment]
Its working perfectly fine. I guess the readme is not updated for vite+react. are you running npm run dev to start the client and nodemon server.js for server ? @Meetpidev

**Comment by Meetpidev** [comment]
@nandit27 yes for client npm run dev and for server nodemon server.js..

**Comment by Meetpidev** [comment]
@nandit27 Even i tested api.. error occurs..  make .env file in server folder and set REACT_APP_API_URL=http://localhost:3000..

![image](https://github.com/user-attachments/assets/1959bc0e-eac8-4a56-9953-68b250f665e8)

**Comment by Meetpidev** [comment]
@bhavyaGP Requested to help me to solve it..

**Comment by Meetpidev** [comment]
@bhavyaGP Requested to help me to solve it..

**Comment by bhavyaGP** [comment]
8780034261 contact me!!
