### ISSUE TITLE
Provide Fallback UI in Case of Errors

### ISSUE THREAD

**Issue by bhavyaGP** [clubgamma/Internet-Speed-Tester#3]
Implement error handling on the frontend to display an informative error message in the UI if the speed test fails.

**Comment by MitM123** [comment]
Can assign this task to me @bhavyaGP

**Comment by MitM123** [comment]
@bhavyaGP

**Comment by MitM123** [comment]
Task completed @bhavyaGP

**Comment by MitM123** [comment]
That is level 2 issue am I right but increase only 3
