### ISSUE TITLE
Mobile-First UI/UX Enhancements

### ISSUE THREAD

**Issue by bhavyaGP** [clubgamma/Internet-Speed-Tester#5]
The current UI may not be fully optimized for mobile users. While the test results work fine on desktop, mobile users may experience layout or usability issues.

**Comment by PriyanshuValiya** [comment]
@bhavyaGP Assign me this issue.

**Comment by MitM123** [comment]
Can this task assign to me @bhavyaGP

**Comment by MitM123** [comment]
Can assign this task to me @bhavyaGP

**Comment by MitM123** [comment]
Task completed @bhavyaGP
