### ISSUE TITLE
Location as well as IP Address is not displayed in Results

### ISSUE THREAD

**Issue by nandit27** [clubgamma/Internet-Speed-Tester#8]
As we click on the button of Speed test, It only displays Download, Upload Speed and the Ping. But the fields of location and IP Address are not displayed. So, for that we need to use an external API to display both the details and show up in the results menu.

**Comment by nandit27** [comment]
@bhavyaGP I have solved this issue, if possible you can assign this issue to me so that I can update the code.

**Comment by bhavyaGP** [comment]
@nandit27 just raise pr

**Comment by nandit27** [comment]
@bhavyaGP I am not able to push due to access denied. 
<img width="913" alt="Screenshot 2024-10-11 at 6 35 19 PM" src="https://github.com/user-attachments/assets/24d2b8f2-31df-4bd3-97e8-dd69fa0585d5">

**Comment by bhavyaGP** [comment]
i have assigned already
